version: '3'
services:
  minio:
    image: "minio/minio:latest"
    container_name: "minio"
    ports:
      - "9001:9001"
      - "9000:9000"
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"
    volumes:
      - "minio:/data"
    environment:
      - MINIO_ROOT_USER = "minio"
      - MINIO_ROOT_PASSWORD = "minio123"
  mc:
    depends_on:
      - "minio"
    image: "minio/mc"
    container_name: "mc"
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://<add-docker-container-ip>:9000 minio minio123) do echo "...waiting..." && sleep 1; done;
      /usr/bin/mc rm -r --force minio/bucket;
      /usr/bin/mc mb minio/bucket;
      /usr/bin/mc policy set public minio/bucket;
      tail -f /dev/null
      "
volumes:
  minio:
    driver: local
